# Generated by Django 4.0.4 on 2022-06-12 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_mascota_fotomascota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Categoria')),
                ('descCategoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('idMarca', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de marca')),
                ('nombreMarca', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('idStock', models.AutoField(primary_key=True, serialize=False, verbose_name='Id Stock')),
                ('cantidadStock', models.IntegerField(verbose_name='Cantidad Stock')),
            ],
        ),
        migrations.CreateModel(
            name='TipoMascotaPRO',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Mascota')),
                ('descTipoMascota', models.CharField(max_length=30, verbose_name='Descripción de Mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id del Producto')),
                ('nombreProducto', models.CharField(max_length=40, verbose_name='Nombre del Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del Producto')),
                ('fotoMascota', models.ImageField(null=True, upload_to='productos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.marca')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.stock')),
            ],
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipoMascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.tipomascotapro'),
        ),
    ]
