# Generated by Django 4.0.4 on 2022-06-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_categoria_marca_stock_tipomascotapro_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(verbose_name='Cantidad Stock'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
