# Generated by Django 4.0.4 on 2022-06-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_categoria_producto_categoriaproducto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('idOng', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la Ong')),
                ('nombreOng', models.CharField(max_length=40, verbose_name='Nombre de la Ong')),
                ('fechaOng', models.DateField(verbose_name='Fecha  de la Organizacion')),
                ('descripcionOng', models.TextField(verbose_name='Descripcion de la Ong')),
                ('fotoOng', models.ImageField(null=True, upload_to='Organizacion')),
            ],
        ),
    ]
