# Generated by Django 4.0.4 on 2022-06-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_organizacion_fotoong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='fotoOng',
            field=models.ImageField(null=True, upload_to='Organizacion'),
        ),
    ]
