# Generated by Django 4.0.4 on 2022-07-05 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='usuarioDonador',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
