# Generated by Django 4.0.4 on 2022-07-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_donacion_usuariodonador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raza',
            name='tipoMascota',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Raza',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='TipoMascota',
        ),
    ]
