# Generated by Django 4.0.4 on 2022-07-10 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_raza_tipomascota_delete_mascota_delete_raza_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='correoDonador',
            field=models.EmailField(max_length=254, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='monto',
            field=models.IntegerField(choices=[[0, 1000], [1, 2000], [2, 5000], [3, 10000], [4, 20000]], verbose_name='Monto a donar'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='nombreDonador',
            field=models.CharField(max_length=50, verbose_name='Nombre y Apellido'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='ong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organizacion', verbose_name='ONG'),
        ),
        migrations.AlterField(
            model_name='donacion',
            name='usuarioDonador',
            field=models.CharField(max_length=50, verbose_name='Usuario'),
        ),
    ]
