# Generated by Django 4.0.4 on 2022-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_donacion_correodonador_alter_donacion_monto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='fechaDonacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
