# Generated by Django 4.0.5 on 2022-07-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_donacion_fechadonacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='fechaOng',
            field=models.DateField(verbose_name='Fecha de Ingreso Ong'),
        ),
    ]
