# Generated by Django 4.0.4 on 2022-07-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_organizacion_fechaong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stockProducto',
            field=models.PositiveIntegerField(verbose_name='Cantidad Stock'),
        ),
    ]
